### ISSUE TITLE
Small heart and Large heart look the same 

### ISSUE THREAD

**Issue by evelynmitchell** [jeffgerickson/algorithms#28]
They are similar in shape and colour, and differ only slightly in size, so you need to have them side by side to notice the difference.

A different symbol for the open problems would be appreciated.

**Comment by jeffgerickson** [comment]
Hmm.  The **open**-problem heart is actually double the size of the **merely-fun**-problem heart. One has the size and alignment of a capital letter; the other has the size and alignment of a superscript.  Maybe the problem is the **merely-really-hard**-problem heart, which is halfway between.

Perhaps the right way to fix this issue is to mirror the very last problem in Chapter 2, which has an explicit "Open Problem:" label in addition to the giant heart.

**Comment by jeffgerickson** [comment]
Since I was only using the open-problem heart once, I adopted the larger heart for really hard problems.

**Comment by jeffgerickson** [comment]
Open problems are explicitly called out in the exercises and in the index.
