### ISSUE TITLE
Ch1.9 p40 Kolmogorov conjecture wrong

### ISSUE THREAD

**Issue by MarkJeronimus** [jeffgerickson/algorithms#68]
> "Andrei Kolmogorov, one of the giants of 20th century mathematics, publicly conjectured that there is no algorithm to multiply two n-digit numbers in o(n^2) time."

This should end with: "in less than o(n^2) time" or "asymptotically better than o(n^2) time".

Ref: https://en.wikipedia.org/wiki/Karatsuba_algorithm

**Comment by jeffgerickson** [comment]
The sentence is correct as-is.  That's a little-oh, not a big-Oh.

https://en.wikipedia.org/wiki/Big_O_notation#Little-o_notation

**Comment by MarkJeronimus** [comment]
What i meant is that the book says "in o() time" while it should be "in at least o() time". Now it reads as if it cannot be calculated in o(n^2) time but can be calculated in any other time complexity.

**Comment by plin25** [comment]
o(·) is an upper bound. Saying "in at least o() time" is like saying "in at least strictly less than 5", which is meaningless.

When Kolmogorov did in fact conjecture that it could not be calculated in o(n^2) time, it was already known that it could be calculated in any other time complexity. In particular, since grade school multiplication is a Ɵ(n^2) algorithm, it can be computed in Ω(n^2) time by running grade school multiplication and then burning empty cycles.
