### ISSUE TITLE
Mischaracterization of Merge routine

### ISSUE THREAD

**Issue by julianoch** [jeffgerickson/algorithms#93]
Chapter 1
Page number: 27-28

Error description: Merge routine contains for loops but it is still iterative and not recursive as you are saying. The fact that you used induction for the proof of correctness doesn't make it recursive either.

As a side note, when X is reduced to Y, you can treat Y as a black box, but in the particular case of recursion, I don't think it is appropriate to characterize the recursive call as a black box, for the simple reason that we are actually implementing that same box which will process the recursive call. When the egyptian scribe uses recursion, he will not be handing the smaller input to a junior scribe, instead he will be processing the recursive call himself, by following the same instructions as for the main call.

**Comment by echuber2** [comment]
I think that your personal definition of "recursive" is not really on target with how it is used in this course's materials (for this _or_ other algorithms courses at other major CS programs), and in addition you're missing the point of how we prove the correctness of a recursive function and communicate this reasoning to students.

The MergeSort routine presented is itself recursive because it calls itself. (Period.) The fact that there's a loop inside the Merge helper function doesn't matter at all. Also, recursive functions can involve iteration as well. These aren't mutually exclusive concepts. The purpose of the text is not to beat a drum for the elimination of all loops in favor of purely recursive syntax. (What would be the next step after that; insisting that the book must be written entirely in lambda calculus?) The purpose is to explain how algorithms with recursive properties work and how they can be analyzed for complexity and be proven correct.

We actually _must_ view the recursive call as a blackbox, because it's impossible to prove the correctness of a recursive function without _assuming_ that the recursive call works. There is an exact analogy with an inductive hypothesis. We can't prove that it works until we first assume that it works. This is something that students struggle with, which is why Prof. Erickson goes to great lengths to explain the concept with metaphors.

**Comment by julianoch** [comment]
Please note that I never ever mentioned MergeSort in this ticket at all. I have been all along talking about the routine Merge specifically. Also, I never said that loops are the problem. You need to read carefully and review your responses in the light of this.

The proof of correctness has two steps: the base step and the induction step. The fact that you can assume that the recursive call works in the induction step, doesn't mean that you can make this claim in the absolute outside the context of the induction step. 

The correctness of the recursive call is implied by the proof of correctness for the main call. So, we are not assuming the correctness of the recursive call, just as we are not assuming the correctness for the main call, given that they are actually the same box. Therefore a recursive call is not the same thing as a black box type of reduction.

**Comment by echuber2** [comment]
This sentence could be edited to more accurately reflect that the merge subroutine is not internally using a recursive call as written:

> The merge algorithm is also recursive—identify the first element of the output array, and then recursively merge the rest of the input arrays.

The text's analogy of the recursive call to a blackbox is explicitly illustrating the meaning of the inductive step. It's the assumption (by the inductive hypothesis) that the recursive call is correct _conditioned on_ the input problem's size or other inductive parameters, which relies on the base case, that ultimately allows the main call to be proven correct unconditionally. This is how such a proof is written, literally. The conditional limitations for correctness imposed on the recursive call by the inductive hypothesis are only relieved in the inductive step by showing the correctness extends to the general case.

It's arguably correct to say that the general case reduces to the conditioned case. The point could be illustrated more tiresomely by pretending we have two different functions, rewriting the recursive case with a separate name, such as `SortListOfLengthAtMostN(list, N)`, and writing an undebatable blackbox reduction from the general `Sort(list)` to the constrained `SortListOfLengthAtMostN(list, N)`. But that's essentially how the inductive hypothesis works anyway, and writing functional recursive code is often easiest by making the recursive call wishfully on the smaller problem instance before fully figuring out the details of the rest of the function. The hard thing to wrap one's head around, is that these can ultimately end up being the same function.

Whether it's merely distracting to bring reductions into the discussion in this chapter is debatable. I think the "black box" language should certainly be left in, whether or not references are made to reduction in this chapter. The black box analogy is already used in many other mathematical and scientific contexts besides, say, Karp reductions or something with a more particular definition. Just because the recursive call's black box nature turns out to go away when the proof follows through, doesn't mean it's not a useful pedagogical step.

**Comment by jeffgerickson** [comment]
> Merge routine contains for loops but it is still iterative and not recursive as you are saying

The merge algorithm is _designed_ recursively; it's merely _implemented_ iteratively.  Recursion is an abstraction for thinking about algorithms, not merely an implementation strategy.

> in the particular case of recursion, I don't think it is appropriate to characterize the recursive call as a black box

You are, of course, welcome to your opinion, but I strongly, vehemently disagree.  The power of recursion—as a design strategy—is **precisely** that you can think of the smaller subproblems being solved by a black box. It is **none of your business** how the top n-1 disks are moved. It is **none of your business** how the previous Fibonacci numbers were computed.  It is **none of your business** how the subarrays are sorted. Keeping your nose out of the Recursion Fairy's business frees up neurons to do more interesting things.

This viewpoint is the main pedagogical point of this chapter.  In fact, this is the main point of the first half of the book.  **Trusting the Recursion Fairy makes it easier to think recursively.**  And thinking recursively is the key to designing all sorts of algorithms, including several whose natural implementations are not recursive.

As I said, you're welcome to disagree, but a couple of generations of students have found this viewpoint incredibly helpful.  I'm not changing it.

> When the egyptian scribe uses recursion, he will not be handing the smaller input to a junior scribe

Why not?  How do _you_ know?

**Comment by julianoch** [comment]
It is true that any algorithm written in a recursive form can be rewritten in an iterative form. As presented, the Merge routine is actually in the iterative form. Its correctness can be better proved using a loop invariant.

The pedagogical concern should not take out of the precision and the formalism. I think that the usage of approximative examples and figures of speech such as "blackbox, fairy,..." affects the precision and takes out of the academic value of the work.
